/**
 * Session Type Definitions
 *
 * Types for the Sessions DynamoDB table and related data structures.
 *
 * @module lib/types/session
 */

/**
 * Session workflow status values.
 * Represents the state machine for quote processing.
 */
export type SessionStatus =
  | "CREATED"
  | "ANALYZING"
  | "CALLING"
  | "SUMMARIZING"
  | "DONE"
  | "FAILED";

/**
 * Vehicle information for the damage assessment.
 * All fields are optional as users may not know exact details.
 */
export type Vehicle = {
  /** Vehicle manufacturer (e.g., "Toyota", "Ford") */
  make?: string;
  /** Vehicle model (e.g., "Camry", "F-150") */
  model?: string;
  /** Vehicle year */
  year?: number;
};

/**
 * Auto repair shop information.
 */
export type Shop = {
  /** Unique identifier for the shop */
  id: string;
  /** Shop business name */
  name: string;
  /** Phone number in E.164 format (e.g., +15551234567) */
  phone: string;
  /** Optional physical address */
  address?: string;
};

/**
 * Damage severity levels.
 */
export type DamageSeverity = "minor" | "moderate" | "severe";

/**
 * Structured damage summary generated by Claude.
 */
export type DamageSummary = {
  /** Clear, professional description of the damage */
  description: string;
  /** Assessed severity level */
  severity: DamageSeverity;
  /** List of affected vehicle parts/areas */
  affected_areas: string[];
  /** Estimated type of repair needed */
  estimated_repair_type: string;
};

/**
 * Price range for a quote.
 */
export type PriceRange = {
  /** Low estimate in dollars (null if not provided) */
  low: number | null;
  /** High estimate in dollars (null if not provided) */
  high: number | null;
};

/**
 * Individual shop quote in the final report.
 */
export type ShopQuote = {
  /** Reference to shop ID */
  shop_id: string;
  /** Shop name for display */
  shop_name: string;
  /** Price range estimate */
  price_range: PriceRange;
  /** Estimated repair time in days (null if not provided) */
  timeframe_days: number | null;
  /** Whether the shop can perform the repair */
  can_do_work: boolean;
  /** Whether in-person inspection is required */
  requires_inspection: boolean;
  /** Additional notes from the call */
  notes: string;
  /** AI-generated recommendation score (1-10) */
  recommendation_score: number;
};

/**
 * Best pick recommendations in the report.
 */
export type BestPick = {
  /** Shop ID with the lowest price */
  by_price: string | null;
  /** Shop ID with the fastest turnaround */
  by_time: string | null;
  /** Shop ID with the best overall value */
  overall: string | null;
};

/**
 * Final comparison report structure.
 */
export type Report = {
  /** Brief overview of the quotes obtained */
  summary: string;
  /** Array of individual shop quotes */
  quotes: ShopQuote[];
  /** Best pick recommendations */
  best_pick: BestPick;
  /** Legal disclaimer about rough estimates */
  disclaimer: string;
};

/**
 * Session record in DynamoDB.
 * Partition key: session_id
 */
export type Session = {
  /** Unique session identifier (nanoid) */
  session_id: string;
  /** Auth0 user identifier */
  user_id: string;
  /** User's location (ZIP/city) for shop context */
  location: string;
  /** Optional vehicle information */
  vehicle?: Vehicle;
  /** User's raw damage description */
  description_raw: string;
  /** S3 keys for uploaded damage images */
  image_keys?: string[];
  /** Text description from Freepik image-to-prompt */
  image_prompt?: string;
  /** Claude-generated structured damage summary */
  damage_summary?: DamageSummary;
  /** List of shops to contact */
  shops: Shop[];
  /** Current workflow status */
  status: SessionStatus;
  /** Final comparison report (when status is DONE) */
  report?: Report;
  /** ISO 8601 creation timestamp */
  created_at: string;
  /** ISO 8601 last update timestamp */
  updated_at: string;
};
